# Generated by Django 4.1.2 on 2022-11-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='description',
            new_name='problemArea',
        ),
        migrations.RemoveField(
            model_name='strategymodule',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='strategymodule',
            name='problemArea',
        ),
        migrations.RemoveField(
            model_name='strategymodule',
            name='uses',
        ),
        migrations.AddField(
            model_name='strategy',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='strategy',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='uses',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strategymodule',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategymodule',
            name='volts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='success',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1),
        ),
        migrations.CreateModel(
            name='StrategyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('matrix_met', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1)),
                ('report', models.FileField(blank=True, null=True, upload_to=None)),
                ('points_alloted', models.IntegerField(default=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
            ],
        ),
    ]
