# Generated by Django 4.1.2 on 2022-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_rename_customer_strategy_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='success',
        ),
        migrations.AddField(
            model_name='strategy',
            name='success_high',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='success_low',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='success_mid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
