# Generated by Django 4.1.2 on 2022-11-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_remove_strategy_success_strategy_success_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='features',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='problemArea',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='uses',
        ),
    ]
