# Generated by Django 4.1.2 on 2022-11-28 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0004_remove_strategy_features_remove_strategy_problemarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategyLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
