# Generated by Django 4.1 on 2022-08-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('problemArea', models.TextField()),
                ('currentPlayers', models.TextField()),
                ('difference', models.TextField()),
                ('customer', models.TextField()),
                ('revenueQuestion', models.TextField()),
                ('revenueAnswer', models.TextField()),
                ('stage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketingTitle', models.TextField()),
                ('type', models.CharField(choices=[('M', 'Major'), ('m', 'Minor')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('success', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesTitle', models.TextField()),
                ('type', models.CharField(choices=[('M', 'Major'), ('m', 'Minor')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('success', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField()),
                ('problemArea', models.TextField()),
                ('uses', models.TextField()),
                ('baseModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.basicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('yearOfGraduation', models.DateField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('founder', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('T', 'Tech'), ('S', 'Sales'), ('M', 'Marketing'), ('L', 'Legal & Admin'), ('O', 'Operations')], max_length=1)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('basicModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.basicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups', models.TextField()),
                ('strategyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Major'), ('m', 'Minor')], default='M', max_length=1)),
                ('approxStartDate', models.DateField()),
                ('Customer', models.TextField()),
                ('features', models.TextField()),
                ('description', models.TextField()),
                ('success', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('strategyLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.user')),
                ('strategyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.TextField()),
                ('strategyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('description', models.TextField()),
                ('outcome', models.TextField()),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.sales')),
                ('taskLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.user')),
            ],
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.basicmodel')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='salesLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.user'),
        ),
        migrations.AddField(
            model_name='sales',
            name='salesModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.salesmodel'),
        ),
        migrations.AddField(
            model_name='sales',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel'),
        ),
        migrations.CreateModel(
            name='ResearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalArticles', models.TextField()),
                ('baseModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.basicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researchTitle', models.TextField()),
                ('category', models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], default='P', max_length=1)),
                ('researchTask', models.TextField()),
                ('conclusion', models.TextField()),
                ('researchArtifacts', models.TextField()),
                ('researchLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.user')),
                ('researchModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.researchmodel')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.TextField()),
                ('strategyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('description', models.TextField()),
                ('outcome', models.TextField()),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.marketing')),
                ('taskLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.user')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkedIn', models.TextField()),
                ('Facebook', models.TextField()),
                ('Twitter', models.TextField()),
                ('Instagram', models.TextField()),
                ('Youtube', models.TextField()),
                ('baseModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.basicmodel')),
            ],
        ),
        migrations.AddField(
            model_name='marketing',
            name='marketingLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.user'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='marketingModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.marketingmodel'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel'),
        ),
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencers', models.TextField()),
                ('how', models.TextField()),
                ('strategyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addCustomers', models.TextField()),
                ('strategyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel')),
            ],
        ),
    ]
