# Generated by Django 4.1 on 2022-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicmodel',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='name',
            field=models.CharField(default='adarsh', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='yearOfGraduation',
            field=models.CharField(max_length=4),
        ),
    ]
