# Generated by Django 4.1 on 2022-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_basicmodel_options_basicmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
