# Generated by Django 4.1.2 on 2022-10-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/images/default.png', upload_to='profile/images'),
        ),
    ]
