# Generated by Django 4.1.2 on 2022-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_profile_basicmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='researchArtifacts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
