# Generated by Django 4.1 on 2022-08-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_user_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicmodel',
            options={'ordering': ['name', '-points']},
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategyModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startegy', to='modules.strategymodel'),
        ),
    ]
