# Generated by Django 4.1.2 on 2022-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_research_researchartifacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmodel',
            name='additionalArticles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
