# Generated by Django 4.1.2 on 2022-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_researchmodel_additionalarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='researchArtifacts',
            field=models.FileField(blank=True, null=True, upload_to='research/articles'),
        ),
        migrations.AlterField(
            model_name='researchmodel',
            name='additionalArticles',
            field=models.FileField(blank=True, null=True, upload_to='researchModel/articles'),
        ),
    ]
