# Generated by Django 4.1.2 on 2022-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_research_researchartifacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='researchArtifacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchmodel',
            name='additionalArticles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
