# Generated by Django 4.1 on 2022-08-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_strategy_strategymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategyModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.strategymodel'),
        ),
    ]
