# Generated by Django 4.1 on 2022-08-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_strategy_strategymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Influencers',
            new_name='Influencer',
        ),
        migrations.RenameModel(
            old_name='Segments',
            new_name='Partner',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='Partners',
            new_name='Segment',
        ),
        migrations.RenameModel(
            old_name='Ups',
            new_name='Up',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='segments',
            new_name='partners',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='partners',
            new_name='segments',
        ),
        migrations.RenameField(
            model_name='strategymodel',
            old_name='baseModel',
            new_name='basicModel',
        ),
        migrations.DeleteModel(
            name='AddCustomers',
        ),
    ]
