# Generated by Django 4.1 on 2022-08-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_rename_influencers_influencer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchmodel',
            old_name='baseModel',
            new_name='basicModel',
        ),
    ]
