# Generated by Django 4.1 on 2022-08-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_rename_basemodel_researchmodel_basicmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingmodel',
            old_name='baseModel',
            new_name='basicModel',
        ),
        migrations.RenameField(
            model_name='salesmodel',
            old_name='baseModel',
            new_name='basicModel',
        ),
    ]
