# Generated by Django 4.1 on 2022-08-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_rename_basemodel_marketingmodel_basicmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtask',
            name='marketingModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modules.marketingmodel'),
            preserve_default=False,
        ),
    ]
