# Generated by Django 4.1 on 2022-08-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_marketingtask_marketingmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingmodel',
            options={'ordering': ['basicModel']},
        ),
        migrations.AlterModelOptions(
            name='researchmodel',
            options={'ordering': ['basicModel']},
        ),
        migrations.AlterModelOptions(
            name='salesmodel',
            options={'ordering': ['basicModel']},
        ),
        migrations.AlterModelOptions(
            name='strategymodel',
            options={'ordering': ['basicModel']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='salestask',
            name='salesModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modules.salesmodel'),
            preserve_default=False,
        ),
    ]
