# Generated by Django 4.1 on 2022-09-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_alter_marketingmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basicModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='modules.basicmodel'),
        ),
    ]
