# Generated by Django 4.1.2 on 2022-11-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0003_startup_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('product_type', models.CharField(choices=[('S', 'Software'), ('S', 'Service'), ('E', 'Education'), ('H', 'Hardware'), ('E', 'Electronics')], max_length=50)),
                ('problemArea', models.TextField()),
                ('phase', models.CharField(choices=[('I', 'Ideation'), ('D', 'Design'), ('MVP', 'MVP (Minimum Viable Product)'), ('PoC', 'Proof of concept'), ('PMF', 'Product Market Fit'), ('C', 'Customer Acquisition'), ('S', 'Scaling')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('version', models.CharField(default='0.0.1', max_length=50)),
                ('deployed_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.startup')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50, null=True)),
                ('designs', models.FileField(null=True, upload_to=None)),
                ('figma', models.URLField(null=True)),
                ('canva', models.URLField(null=True)),
                ('final', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productmodule'),
        ),
    ]
