# Generated by Django 4.1.2 on 2022-11-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default=product.models.generate_key, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(upload_to=None)),
                ('is_ss', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, null=True)),
                ('cate', models.CharField(choices=[('V', 'Version Updated'), ('F', 'Feature Added'), ('FC', 'Feature Completed'), ('P', 'Product Status Changed'), ('D', 'Designs Added')], max_length=50)),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.feature')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='problemArea',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.SlugField(default=product.models.generate_key, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.CharField(choices=[('E', 'Ecommerce'), ('Sm', 'Social media'), ('S', 'SaaS'), ('T', 'Travel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('D', 'Desktop application'), ('S', 'Service'), ('I', 'IOS application'), ('W', 'Website'), ('A', 'Android application'), ('H', 'Hardware')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='volts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='productModule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productmodule'),
        ),
        migrations.DeleteModel(
            name='ProductDesign',
        ),
        migrations.AddField(
            model_name='timeline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
