# Generated by Django 4.1.2 on 2022-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_feature_image_timeline_remove_product_problemarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deployed_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
