# Generated by Django 4.1.2 on 2022-10-29 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idea', models.TextField()),
                ('problemArea', models.TextField()),
                ('currentPlayers', models.TextField()),
                ('difference', models.TextField()),
                ('customer', models.TextField()),
                ('revenueQuestion', models.TextField()),
                ('revenueAnswer', models.TextField()),
                ('stage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name', '-points'],
            },
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ups', to='backend.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='backend.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('yearOfGraduation', models.CharField(max_length=4)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('founder', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('T', 'Tech'), ('S', 'Sales'), ('M', 'Marketing'), ('L', 'Legal & Admin'), ('O', 'Operations')], max_length=1)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='profile/images/default.png', upload_to='profile/images')),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='backend.startup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='backend.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencers', models.TextField()),
                ('how', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='backend.startup')),
            ],
        ),
    ]
