# Generated by Django 4.1.2 on 2022-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='revenueAnswer',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='revenueQuestion',
            new_name='revenue1',
        ),
        migrations.AddField(
            model_name='startup',
            name='founded',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='revenue2',
            field=models.TextField(null=True),
        ),
    ]
