# Generated by Django 4.1.2 on 2022-11-09 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_rename_revenueanswer_startup_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='people'),
        ),
    ]
