# Generated by Django 4.1.2 on 2022-11-23 08:07

import backend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_startup_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('link', models.URLField()),
                ('date_time', models.DateTimeField()),
                ('instant', models.BooleanField(default=False)),
                ('mobs_only', models.BooleanField(default=False)),
                ('importance', models.CharField(choices=[('I', 'Important'), ('D', 'Discussion'), ('N', 'Normal'), ('D', 'Daily'), ('O', 'Optional')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='key',
            field=models.SlugField(default=backend.models.generate_key, editable=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='mobs',
            field=models.ManyToManyField(related_name='mobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startup',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
