# Generated by Django 4.1.2 on 2022-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_meetup_startup_key_startup_mobs_startup_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='logo',
            field=models.ImageField(null=True, upload_to='startup/logo'),
        ),
        migrations.AddField(
            model_name='startup',
            name='vision',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
