# Generated by Django 4.1.2 on 2022-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_startup_logo_startup_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='founded',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
