# Generated by Django 4.1.2 on 2022-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_startup_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='idea',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='vision',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
