# Generated by Django 4.1.2 on 2022-11-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_alter_startup_idea_alter_startup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField(unique=True)),
                ('starred', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('support', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('want_to_work', models.ManyToManyField(related_name='want_to_work', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
