# Generated by Django 4.1.2 on 2022-11-28 16:44

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='key',
            field=models.SlugField(default=backend.models.generate_idea_key, editable=False),
        ),
    ]
