# Generated by Django 4.1.2 on 2022-10-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketingTitle', models.TextField()),
                ('type', models.CharField(choices=[('M', 'Major'), ('m', 'Minor')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('success', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('marketingLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkedIn', models.TextField()),
                ('Facebook', models.TextField()),
                ('Twitter', models.TextField()),
                ('Instagram', models.TextField()),
                ('Youtube', models.TextField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.startup')),
            ],
            options={
                'ordering': ['startup'],
            },
        ),
        migrations.CreateModel(
            name='MarketingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('description', models.TextField()),
                ('outcome', models.TextField()),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketing')),
                ('marketingModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingmodule')),
                ('taskLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.profile')),
            ],
        ),
        migrations.AddField(
            model_name='marketing',
            name='marketingModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingmodule'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategymodule'),
        ),
    ]
