# Generated by Django 4.1.2 on 2022-11-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy'),
        ),
    ]
