# Generated by Django 4.1.2 on 2022-11-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0002_alter_marketing_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(choices=[('L', 'LinkedIn'), ('B', 'Blogs'), ('F', 'Facebook'), ('T', 'Twitter'), ('I', 'Instagram'), ('Y', 'Youtube'), ('R', 'Reddit'), ('O', 'Offline')], max_length=50)),
                ('org_social_link', models.URLField(null=True)),
                ('configured', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('low', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=50)),
                ('points_alloted', models.IntegerField(default=5)),
                ('points', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='success',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='type',
        ),
        migrations.RemoveField(
            model_name='marketingmodule',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='marketingmodule',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='marketingmodule',
            name='LinkedIn',
        ),
        migrations.RemoveField(
            model_name='marketingmodule',
            name='Twitter',
        ),
        migrations.RemoveField(
            model_name='marketingmodule',
            name='Youtube',
        ),
        migrations.AddField(
            model_name='marketing',
            name='key',
            field=models.SlugField(default=marketing.models.generate_key, editable=False),
        ),
        migrations.AddField(
            model_name='marketing',
            name='major',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketingmodule',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingmodule',
            name='volts',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MarketingTask',
        ),
        migrations.AddField(
            model_name='social',
            name='marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketing'),
        ),
        migrations.AddField(
            model_name='social',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingmodule'),
        ),
    ]
