# Generated by Django 4.1.2 on 2022-11-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_social_completed_social_completed_posts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('matrix_met', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1)),
                ('report', models.FileField(blank=True, null=True, upload_to=None)),
                ('points_alloted', models.IntegerField(default=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketing')),
            ],
        ),
    ]
