# Generated by Django 4.1.2 on 2022-11-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_marketingresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingResult',
        ),
    ]
