# Generated by Django 4.1.2 on 2022-11-24 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_platform_social_remove_marketing_success_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_researchmodule_head_researchmodule_volts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='researchTask',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='research',
            name='researchArtifacts',
        ),
        migrations.RemoveField(
            model_name='research',
            name='researchLeader',
        ),
        migrations.RemoveField(
            model_name='research',
            name='researchTitle',
        ),
        migrations.RemoveField(
            model_name='research',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='researchmodule',
            name='additionalArticles',
        ),
        migrations.AddField(
            model_name='research',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='img',
            field=models.ImageField(null=True, upload_to='startup/content/img'),
        ),
        migrations.AddField(
            model_name='research',
            name='marketing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.marketing'),
        ),
        migrations.AddField(
            model_name='research',
            name='video',
            field=models.FileField(null=True, upload_to='startup/content/video'),
        ),
        migrations.AddField(
            model_name='research',
            name='volts',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.CharField(choices=[('B', 'Brief'), ('I', 'Image/Poster'), ('V', 'Video'), ('R', 'Research')], default='P', max_length=1),
        ),
    ]
