# Generated by Django 4.1.2 on 2022-11-26 11:43

from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_rename_researchtask_research_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='key',
            field=models.SlugField(default=research.models.generate_key, editable=False),
        ),
    ]
