# Generated by Django 4.1.2 on 2022-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_remove_research_marketing_research_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='completed',
        ),
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('D', 'Draft'), ('T', 'Task')], default='T', max_length=50),
        ),
        migrations.AlterField(
            model_name='research',
            name='task',
            field=models.TextField(unique=True),
        ),
    ]
