# Generated by Django 4.1.2 on 2022-11-27 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_research_completed_research_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='conclusion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
