# Generated by Django 4.1.2 on 2022-10-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesTitle', models.TextField()),
                ('type', models.CharField(choices=[('M', 'Major'), ('m', 'Minor')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('success', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('salesLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SalesModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.startup')),
            ],
            options={
                'ordering': ['startup'],
            },
        ),
        migrations.CreateModel(
            name='SalesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('description', models.TextField()),
                ('outcome', models.TextField()),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
                ('salesModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesmodule')),
                ('taskLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.profile')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='salesModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesmodule'),
        ),
        migrations.AddField(
            model_name='sale',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategymodule'),
        ),
    ]
